[package]
name = "sdith"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-bigint = "0.5.5"
matrix = "0.22.0"
modular = "1.0.0"
num-traits = "0.2.19"
polynomen = "1.1.0"
rand = "0.8.5"
tiny-keccak = { version = "2.0.2", features = ["shake", "sha3"] }
