[package]
name = "sdith"
version = "0.0.0"
edition = "2021"

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["shake", "sha3"] }
queues = "1.0.2"
clap = { version = "4.5.20", features = ["derive"] }
rand = "0.8.5"
base64 = "0.22.1"
num-traits = "0.2.19"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
criterion-cycles-per-byte = "0.6.1"
nist-pqc-seeded-rng = "0.2.0"

[[bench]]
name = "benchmark"
harness = false

[build-dependencies]
const-gen = "1.6.5"
dotenv_codegen = "0.15.0"

[profile.dev]
opt-level = 3

# [profile.release]
# debug = 1
