[package]
name = "sdith"
version = "0.0.0"
edition = "2021"

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["shake", "sha3"] }
queues = "1.0.2"
clap = { version = "4.5.20", features = ["derive"] }
rand = "0.8.5"
base64 = "0.22.1"
num-traits = "0.2.19"
rayon = { version = "1.10.0", optional = true }
blake3 = { version = "1.5.4", optional = true }
criterion-cycles-per-byte = { version = "0.6.1", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
nist-pqc-seeded-rng = "0.2.0"

[[bench]]
name = "benchmark"
harness = false

[build-dependencies]
const-gen = "1.6.5"
dotenv_codegen = "0.15.0"

[profile.dev]
opt-level = 3

[profile.release]
debug = 1 # TODO: remove this

[features]
xof_blake3 = ["dep:blake3"]
hash_blake3 = ["dep:blake3"]
category_one = []
category_three = []
category_five = []
parallel = ["dep:rayon"]
simd = []
cycles_per_byte = ["dep:criterion-cycles-per-byte"] # Benchmarking feature
