[package]
name = "sdith"
version = "0.0.0"
edition = "2021"

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["shake", "sha3"] }
queues = "1.0.2"
clap = { version = "4.5.20", features = ["derive"] }
rand = "0.8.5"
base64 = "0.22.1"
num-traits = "0.2.19"
rayon = { version = "1.10.0", optional = true }
blake3 = { version = "1.5.4", optional = true }
criterion-cycles-per-byte = { version = "0.6.1", optional = true }
hex = { version = "0.4.3", optional = true }
nist-pqc-seeded-rng = { version = "0.2.0", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false

[build-dependencies]
const-gen = "1.6.5"
dotenv_codegen = "0.15.0"
rustc_version = "0.4.1"

[profile.dev]
opt-level = 3

[profile.release]
debug = 1 # TODO: remove this

[features]
default = ["category_one", "optimized"]

# Categories
category_one = []
category_three = []
category_five = []

# Optimization features
optimized = ["simd", "parallel"]
parallel = ["dep:rayon"]
simd = []

# Testing and Benchmarking features
kat = ["dep:hex", "dep:nist-pqc-seeded-rng"]        # Include Known Answer Tests
cycles_per_byte = ["dep:criterion-cycles-per-byte"] # Benchmarking feature

# Experimental features
blake3 = ["xof_blake3", "hash_blake3"]
xof_blake3 = ["dep:blake3"]
hash_blake3 = ["dep:blake3"]
