//! # Constants
//!
//! Ensures that the generated constants are included.
//! The Constants are used for array sizing `[u8; GEN_CONST]`.

// Include our constants
include!(concat!(env!("OUT_DIR"), "/const_gen.rs")); // This is generated by build.rs
