//! # Precomputed
//!
//! Ensures that the generated precomputed values are included.
//! The precomputed values are the following:
//! - The vanishing polynomial F
//! - Leading coefficients for S

// Include our precomputed constants
include!(concat!(env!("OUT_DIR"), "/precomputed_gen.rs")); // This is generated by build.rs
